[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wavegui"
dynamic = ["version"]
description = "web based ui framework, write pretty ui without knoledge of css/html."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "Wei Zhuo", email = "zeaphoo@qq.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "basepy>=0.3.4",
    "starlette>=0.13.8",
    "uvicorn[standard]>=0.12.2",
    "itsdangerous",
    "aiofiles",
    "python-multipart"
]

[project.optional-dependencies]
test = [
    "pytest>=3"
]

[tool.hatch.build.targets.wheel]
packages = ["wavegui"]

[tool.hatch.build]
include = [
  "wavegui/www/**"
]

[tool.hatch.version]
path = "wavegui/__init__.py"
