debug = true
port = 9000
run_editor = true
db_url = 'postgres://postgres:postgres@127.0.0.1:5432/highorder?min_size=10&max_size=30'
data_dir = "./data"
#content_url = ''
webapp_root = '../webapp/dist/'